export const data = JSON.parse("{\"key\":\"v-8daa1a0e\",\"path\":\"/\",\"title\":\"主页\",\"lang\":\"zh-CN\",\"frontmatter\":{\"home\":true,\"icon\":\"home\",\"title\":\"主页\",\"heroImage\":\"/logo.svg\",\"bgImage\":\"https://theme-hope-assets.vuejs.press/bg/6-light.svg\",\"bgImageDark\":\"https://theme-hope-assets.vuejs.press/bg/6-dark.svg\",\"bgImageStyle\":{\"background-attachment\":\"fixed\"},\"heroText\":\"我的博客简历\",\"tagline\":\"您好，我叫姚凤桥，毕业于🎓湖北第二师范学院。在校期间积累了不错的编程经验，可熟练运用主流分布式技术栈，独立开发项目。\",\"actions\":[{\"text\":\"查看简历 👣\",\"link\":\"./md/\",\"type\":\"primary\"},{\"text\":\"我的项目 💐\",\"link\":\"https://openai.gaga.plus/\"}],\"highlights\":[{\"header\":null,\"bgImage\":\"/assets/bg/6-light.svg\",\"bgImageDark\":\"/assets/bg/6-dark.svg\",\"features\":[{\"title\":\"OpenAI助手 & OpenAI营销平台\",\"icon\":\"table-columns\",\"details\":\"24年1月，以DDD领域驱动设计架构，开发完成AI助手、营销平台系统。运用了全面的分布式技术栈。\",\"link\":\"http://openai.yaofengqiao.top:3002/#/chat/0\"}]}],\"copyright\":false,\"footer\":\"<div class=\\\"content\\\"><a href=\\\"http://beian.miit.gov.cn\\\" target=\\\"_blank\\\">京ICP备1903****号</a> | MIT 协议, 版权所有 © 2024 姚凤桥，All rights reserved.</div>\",\"description\":\"个人在大学/实习期间，参与过多次的技术类赛事项目，熟练使用各类技术框架，积累了丰富的开发经验。同时兼具着对技术的喜爱，长期对技术源码进行钻研学习吸收其中的设计精髓。尤其对 MyBatis 源码学习后，开发了一款监控 SQL 慢查询以及优化建议插件。并将此插件发布到了 IDEA Plugin 插件市场，半年获得了3000次下载量，获得了非常好的认可，个人...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"我的简历\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"主页\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"个人在大学/实习期间，参与过多次的技术类赛事项目，熟练使用各类技术框架，积累了丰富的开发经验。同时兼具着对技术的喜爱，长期对技术源码进行钻研学习吸收其中的设计精髓。尤其对 MyBatis 源码学习后，开发了一款监控 SQL 慢查询以及优化建议插件。并将此插件发布到了 IDEA Plugin 插件市场，半年获得了3000次下载量，获得了非常好的认可，个人...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"website\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"姚凤桥\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"WebPage\\\",\\\"name\\\":\\\"主页\\\",\\\"description\\\":\\\"个人在大学/实习期间，参与过多次的技术类赛事项目，熟练使用各类技术框架，积累了丰富的开发经验。同时兼具着对技术的喜爱，长期对技术源码进行钻研学习吸收其中的设计精髓。尤其对 MyBatis 源码学习后，开发了一款监控 SQL 慢查询以及优化建议插件。并将此插件发布到了 IDEA Plugin 插件市场，半年获得了3000次下载量，获得了非常好的认可，个人...\\\"}\"]]},\"headers\":[],\"readingTime\":{\"minutes\":1.67,\"words\":501},\"filePathRelative\":\"README.md\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
